# Generated by Django 6.0.6 on 2026-06-23 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=150)),
                ('currentpoint', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicid', models.AutoField(primary_key=True, serialize=False)),
                ('topictitle', models.CharField(max_length=200)),
                ('topicdetailtext', models.TextField()),
                ('status', models.CharField(default='open', max_length=20)),
                ('deadtime', models.DateTimeField()),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('optid', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('topicid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='bookmaker.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betpoint', models.IntegerField(default=0)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('optid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmaker.option')),
            ],
            options={
                'unique_together': {('uid', 'optid')},
            },
        ),
    ]
