# Generated by Django 6.0.6 on 2026-06-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaker', '0002_chat_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
