# Generated by Django 6.0.6 on 2026-06-24 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaker', '0003_option_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='shared_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_chats', to='bookmaker.topic'),
        ),
    ]
