# Generated by Django 6.0.6 on 2026-06-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaker', '0004_chat_shared_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
