"""
Django settings for sns_project project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# BASE_DIR はこの Django プロジェクトのルートディレクトリです。
BASE_DIR = Path(__file__).resolve().parent.parent

# アプリケーションの機密キー。公開リポジトリに置かないのが原則です。
SECRET_KEY = 'django-insecure--3#p6n-f9ga@7!a%1ll9#i*$dzbe-f4#a#2uts!=ptno!w0#o+'

# デバッグモード。開発環境では True にしてエラー情報を確認します。
DEBUG = True

# 許可するホスト名のリスト。'*' はすべて許可しますが、本番では絞るべきです。
ALLOWED_HOSTS = ['*']



# インストール済みアプリケーション。
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookmaker',
]


# リクエスト/レスポンスの処理フローに入るミドルウェアの順番を定義します。
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# プロジェクトの URL 設定を読み込む場所。
ROOT_URLCONF = 'sns_project.urls'

# Django のテンプレートエンジン設定。
# 'DIRS' にはプロジェクト共通のテンプレートフォルダを追加しています。
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'sns_project' / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI アプリケーションのパス。同期サーバーがこの値を使って Django を起動します。
WSGI_APPLICATION = 'sns_project.wsgi.application'


# データベース設定。ここでは SQLite を使い、環境によってファイルパスを切り替えています。
# - 通常の開発環境ではプロジェクト直下の db.sqlite3 を使います。
# - RENDER のような特定のホスティング環境では data/db.sqlite3 に切り替えます。

import os

if 'RENDER' in os.environ:
    DB_PATH = BASE_DIR / 'data' / 'db.sqlite3'
else:
    DB_PATH = BASE_DIR / 'db.sqlite3'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_PATH,
    }
}


# パスワード検証の設定。開発環境でも基本的なチェックを有効にしています。
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 静的ファイルの設定。CSS や JavaScript を配置する場所を指定します。
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# メディアファイルの設定。ユーザーがアップロードした画像などを保存します。
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# sns_project/settings.py の一番下に追記

# 認証後のリダイレクト先やログイン必須時の遷移先を設定します。
LOGIN_REDIRECT_URL = 'top_page'  # ログイン後に移動する先
LOGOUT_REDIRECT_URL = 'login'     # ログアウト後に移動する先
LOGIN_URL = 'login'              # ログイン必須ビューへリダイレクトするときに使う URL 名


import os
# 本番環境で `python manage.py collectstatic` を実行したときに、すべての静的ファイルをまとめて置くディレクトリです。
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# WhiteNoise を使って静的ファイルを圧縮・キャッシュ対応で配信します。
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# JSON レスポンスに日本語を含めるときに Unicode をそのまま出力します。
JSON_AS_ASCII = False

# 適切な自動主キーのデフォルト（警告回避）
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'